---
- name: provisioning of virtual machine for VA creation
  hosts: ansible-local
  sudo: True
  vars:
    jre_package: jre.rpm
    mariadb_server_package: mariadb-server.rpm
    tomcat_package: tomcat.tar.gz
    target_temp: /tmp/packages
  tasks:
    - name: install JRE 8
      yum: >
        name={{ target_temp }}/{{ jre_package }} 
        state=present
    - name: create directiory for Tomcat installation
      file: >
        path=/usr/local/tomcat7
        state=directory
        mode=0755
    - name: install Tomcat 7
      unarchive: >
        src={{ target_temp }}/{{ tomcat_package }}
        dest=/usr/local/tomcat7
        copy=no