---
- name: YML file for preliminary steps of provisioning
  hosts: centos6-server
  sudo: True
  vars_files:
    - variables.yml
  tasks:
    - name: create temp dir
      file: >
        path={{ target_temp }}
        state=directory
        mode=0755
    - name: copy packages and configuration files to temp dir
      copy: >
        src={{ item }}
        dest={{ target_temp }}
      with_fileglob: source_packages
      