---
- name: provisioning of virtual machine for VA creation
  hosts: ansible-local
  sudo: True
  vars_files:
    - variables.yml
  tasks:
    - name: create temp dir
      file: >
        path={{ packages_dir }}
        state=directory
        mode=0755
    - name: copy packages and configuration files to temp dir
      copy: >
        src={{ item }}
        dest={{ packages_dir }}
      with_fileglob: source_packages
    - name: install JRE 8
      yum: >
        name={{ packages_dir }}/{{ jre_package }} 
        state=present
    - name: create directiory for Tomcat installation
      file: >
        path=/opt/tomcat
        state=directory
        mode=0755
    - name: install Tomcat 7
      unarchive: >
        src={{ packages_dir }}/{{ tomcat_package }}
        dest=/opt/tomcat
        copy=no
    - name: remove temp dir
      file: >
        path={{ packages_dir }}
        state=absent